//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobScheduleTimeline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScheduleDependency
    {
        public int JobScheduleDependencyId { get; set; }
        public int JobScheduleId { get; set; }
        public int DependencyId { get; set; }
        public bool IsActive { get; set; }
    
        public virtual JobSchedule JobSchedule { get; set; }
        public virtual JobSchedule JobSchedule1 { get; set; }
    }
}
