//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobScheduleTimeline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScheduleStamp
    {
        public int JobScheduleStampId { get; set; }
        public int JobScheduleId { get; set; }
        public string Name { get; set; }
        public Nullable<long> ValueInt { get; set; }
        public string ValueInfo { get; set; }
        public Nullable<System.DateTime> ValueDate { get; set; }
        public Nullable<bool> ValueBool { get; set; }
        public Nullable<int> JobScheduleLogId { get; set; }
    
        public virtual JobSchedule JobSchedule { get; set; }
        public virtual JobScheduleLog JobScheduleLog { get; set; }
    }
}
