//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobScheduleTimeline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScheduleMethod
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobScheduleMethod()
        {
            this.JobSchedules = new HashSet<JobSchedule>();
        }
    
        public int JobScheduleMethodId { get; set; }
        public string MethodName { get; set; }
        public string AssemblyName { get; set; }
        public string ClassName { get; set; }
        public string Description { get; set; }
        public string DescriptionEng { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobSchedule> JobSchedules { get; set; }
    }
}
