//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobScheduleTimeline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobScheduleLog
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public JobScheduleLog()
        {
            this.JobScheduleStamps = new HashSet<JobScheduleStamp>();
            this.JobScheduleLogItems = new HashSet<JobScheduleLogItem>();
        }
    
        public int JobScheduleLogId { get; set; }
        public int JobScheduleId { get; set; }
        public System.DateTime Started { get; set; }
        public Nullable<System.DateTime> Ended { get; set; }
        public int DateId { get; set; }
        public Nullable<int> HostId { get; set; }
        public int UserId { get; set; }
        public short JobScheduleLogStatusId { get; set; }
    
        public virtual JobSchedule JobSchedule { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobScheduleStamp> JobScheduleStamps { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobScheduleLogItem> JobScheduleLogItems { get; set; }
        public virtual JobScheduleLogStatu JobScheduleLogStatu { get; set; }
    }
}
