//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobScheduleTimeline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InternshipTaskEntities : DbContext
    {
        public InternshipTaskEntities()
            : base("name=InternshipTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobSchedule> JobSchedules { get; set; }
        public virtual DbSet<JobScheduleChain> JobScheduleChains { get; set; }
        public virtual DbSet<JobScheduleDependency> JobScheduleDependencies { get; set; }
        public virtual DbSet<JobScheduleLog> JobScheduleLogs { get; set; }
        public virtual DbSet<JobScheduleLogItem> JobScheduleLogItems { get; set; }
        public virtual DbSet<JobScheduleLogStatu> JobScheduleLogStatus { get; set; }
        public virtual DbSet<JobScheduleMethod> JobScheduleMethods { get; set; }
        public virtual DbSet<JobScheduleParameter> JobScheduleParameters { get; set; }
        public virtual DbSet<JobScheduleStamp> JobScheduleStamps { get; set; }
    
        public virtual ObjectResult<JobScheduleTimeline1_Result> JobScheduleTimeline(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string resourceIdsCSV)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var resourceIdsCSVParameter = resourceIdsCSV != null ?
                new ObjectParameter("ResourceIdsCSV", resourceIdsCSV) :
                new ObjectParameter("ResourceIdsCSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JobScheduleTimeline1_Result>("JobScheduleTimeline", startDateParameter, endDateParameter, resourceIdsCSVParameter);
        }
    
        public virtual ObjectResult<JobScheduleTimeline1_Result> JobScheduleTimeline1(Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate, string resourceIdsCSV)
        {
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            var resourceIdsCSVParameter = resourceIdsCSV != null ?
                new ObjectParameter("ResourceIdsCSV", resourceIdsCSV) :
                new ObjectParameter("ResourceIdsCSV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<JobScheduleTimeline1_Result>("JobScheduleTimeline1", startDateParameter, endDateParameter, resourceIdsCSVParameter);
        }
    }
}
