//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobScheduleTimeline.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class InternshipTaskEntities : DbContext
    {
        public InternshipTaskEntities()
            : base("name=InternshipTaskEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<JobSchedule> JobSchedules { get; set; }
        public virtual DbSet<JobScheduleChain> JobScheduleChains { get; set; }
        public virtual DbSet<JobScheduleDependency> JobScheduleDependencies { get; set; }
        public virtual DbSet<JobScheduleLog> JobScheduleLogs { get; set; }
        public virtual DbSet<JobScheduleLogItem> JobScheduleLogItems { get; set; }
        public virtual DbSet<JobScheduleLogStatu> JobScheduleLogStatus { get; set; }
        public virtual DbSet<JobScheduleMethod> JobScheduleMethods { get; set; }
        public virtual DbSet<JobScheduleParameter> JobScheduleParameters { get; set; }
        public virtual DbSet<JobScheduleStamp> JobScheduleStamps { get; set; }
    }
}
